# Generated by Django 5.0.7 on 2024-12-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message2',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
