# Generated by Django 5.0.7 on 2024-07-28 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Venue Name')),
                ('email', models.EmailField(max_length=225, unique=True, verbose_name='Contact Email')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Contact Phone')),
                ('description', models.TextField(verbose_name='Venue Description')),
                ('dining_seat_count', models.PositiveIntegerField(verbose_name='Dining Seat Count')),
                ('auditorium_seat_count', models.PositiveIntegerField(verbose_name='Auditorium Seat Count')),
                ('condition', models.CharField(max_length=6)),
                ('price', models.IntegerField(verbose_name='Price')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('pincode', models.CharField(max_length=10, verbose_name='Pincode')),
                ('address', models.TextField(verbose_name='Address')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('terms_and_conditions', models.FileField(blank=True, null=True, upload_to='terms_conditions/', verbose_name='Terms and Conditions PDF')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='owners.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.TextField(verbose_name='Facility Description')),
                ('price', models.IntegerField(verbose_name='Facility Price')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='owners.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=115, verbose_name='Event Name')),
                ('event_photo', models.ImageField(upload_to='events/', verbose_name='Event Photo')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='owners.venue')),
            ],
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_photo', models.ImageField(upload_to='venue_images/', verbose_name='Venue Photo')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='owners.venue')),
            ],
        ),
    ]
