# Generated by Django 5.0.7 on 2025-04-07 11:32

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempownerandvenuedetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempownerandvenuedetails',
            name='secure_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
