# Generated by Django 5.0.7 on 2025-09-19 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnavailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_dates', to='owners.venue')),
            ],
            options={
                'unique_together': {('venue', 'date')},
            },
        ),
    ]
