# Generated by Django 5.0.7 on 2024-08-12 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venueimage',
            name='name',
        ),
    ]
