# Generated by Django 5.0.7 on 2024-07-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_venue_facility_event_venueimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
