# Generated by Django 5.0.7 on 2024-12-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpackages',
            name='is_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingpackages',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingpackages',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingpackages',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
