# Generated by Django 5.0.7 on 2024-12-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_bookingpackages_is_editable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempOwnerAndVenueDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_details', models.JSONField(blank=True, null=True)),
                ('venue_details', models.JSONField(blank=True, null=True)),
                ('event_details', models.JSONField(blank=True, null=True)),
                ('facility_details', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
