# Generated by Django 5.0.7 on 2024-08-14 21:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0004_alter_onetimepasswordforowner_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepasswordforowner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
