# Generated by Django 5.0.7 on 2024-08-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0004_venue_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Facility Price'),
        ),
    ]
