# Generated by Django 5.0.7 on 2024-08-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0005_onetimepasswordforowner_created_at_owner_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_under_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='maintenance_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
