# Generated by Django 5.0.7 on 2025-09-19 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_dash', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformfee',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.booking'),
        ),
    ]
