# Generated by Django 5.0.7 on 2025-04-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocking_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
