# Generated by Django 5.0.7 on 2024-08-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='code',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
