# Generated by Django 5.0.7 on 2024-12-06 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_initial'),
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='event_name',
            field=models.CharField(default='Default Event Name', max_length=225),
        ),
        migrations.AddField(
            model_name='booking',
            name='package_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owners.bookingpackages'),
        ),
        migrations.AddField(
            model_name='booking',
            name='times',
            field=models.JSONField(default=list),
        ),
    ]
