# Generated by Django 5.0.7 on 2024-12-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_booking_event_details_booking_event_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dates',
            field=models.JSONField(default=list),
        ),
    ]
