# Generated by Django 5.0.7 on 2024-12-11 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_initial'),
        ('users', '0004_booking_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.venue')),
            ],
        ),
    ]
