# Generated by Django 5.0.7 on 2024-08-05 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0006_venueimage_is_active_venueimage_name'),
        ('users', '0004_onetimepassword_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=225)),
                ('phone', models.CharField(max_length=12)),
                ('additional_phone', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('time', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('condition', models.CharField(max_length=150)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Booking Confirmed', 'Booking Confirmed'), ('Booking Completed', 'Booking Completed'), ('Booking Canceled', 'Booking Canceled')], default='Booking Confirmed', max_length=150)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.venue')),
            ],
        ),
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities', models.CharField(max_length=225)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.booking')),
            ],
        ),
    ]
