# Generated by Django 5.0.7 on 2025-04-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userinquiry_reply_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_canceled_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
