# Generated by Django 5.0.7 on 2025-03-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrooms',
            name='unread_count_user1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatrooms',
            name='unread_count_user2',
            field=models.IntegerField(default=0),
        ),
    ]
