# Generated by Django 5.0.7 on 2025-03-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatrooms_unread_count_user1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrooms',
            name='last_message_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
